build:
  environment:
    RUSTUP_HOME: /opt/render/.rustup
    CARGO_HOME: /opt/render/.cargo
  commands:
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - export PATH="$CARGO_HOME/bin:$PATH"
    - rustup target add x86_64-unknown-linux-gnu